services:
  nodered-homekit:
    build:
      context: ./
      dockerfile: Dockerfile

    # Allow mDNS
    network_mode: host

    # Mount the persistent data volume
    volumes:
      - ./mount:/data:rw
